[book]
authors = ["watonyweng"]
language = "zh-CN"
title = "MdBook 基本使用"
src = "src"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/watonyweng/mdbook"
edit-url-template = "https://github.com/watonyweng/mdbook/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"